# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 15:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('type_of_exercise', models.CharField(choices=[('ST', 'Stomach'), ('BA', 'Back'), ('LE', 'Legs'), ('AR', 'Arms'), ('WH', 'Whole')], max_length=2)),
                ('level', models.BooleanField(verbose_name='Level:')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
